-- Private historical business records. Never feed these into payment/email handlers.
-- Source values remain TEXT, including blanks, leading zeros, dates and money.
CREATE TABLE IF NOT EXISTS wix_import_batches (
 id TEXT PRIMARY KEY, source_hashes TEXT NOT NULL, status TEXT NOT NULL CHECK(status='reconciled'), created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS wix_source_files (
 batch_id TEXT NOT NULL REFERENCES wix_import_batches(id), dataset TEXT NOT NULL,
 original_bytes BLOB NOT NULL, PRIMARY KEY(batch_id,dataset)
);
CREATE TABLE IF NOT EXISTS wix_products (
 batch_id TEXT NOT NULL REFERENCES wix_import_batches(id), source_row INTEGER NOT NULL,
 "handle" TEXT NOT NULL,
 "fieldtype" TEXT NOT NULL,
 "name" TEXT NOT NULL,
 "visible" TEXT NOT NULL,
 "plaindescription" TEXT NOT NULL,
 "categoryslugs" TEXT NOT NULL,
 "primarycategoryslug" TEXT NOT NULL,
 "media" TEXT NOT NULL,
 "mediaalttext" TEXT NOT NULL,
 "ribbon" TEXT NOT NULL,
 "brand" TEXT NOT NULL,
 "price" TEXT NOT NULL,
 "strikethroughprice" TEXT NOT NULL,
 "baseunit" TEXT NOT NULL,
 "baseunitmeasurement" TEXT NOT NULL,
 "totalunits" TEXT NOT NULL,
 "totalunitsmeasurement" TEXT NOT NULL,
 "cost" TEXT NOT NULL,
 "inventory" TEXT NOT NULL,
 "preorderenabled" TEXT NOT NULL,
 "preordermessage" TEXT NOT NULL,
 "preorderlimit" TEXT NOT NULL,
 "sku" TEXT NOT NULL,
 "barcode" TEXT NOT NULL,
 "weight" TEXT NOT NULL,
 "packagelength" TEXT NOT NULL,
 "packagewidth" TEXT NOT NULL,
 "packageheight" TEXT NOT NULL,
 "packageunit" TEXT NOT NULL,
 "productoptionname1" TEXT NOT NULL,
 "productoptiontype1" TEXT NOT NULL,
 "productoptionchoices1" TEXT NOT NULL,
 "productoptionname2" TEXT NOT NULL,
 "productoptiontype2" TEXT NOT NULL,
 "productoptionchoices2" TEXT NOT NULL,
 "productoptionname3" TEXT NOT NULL,
 "productoptiontype3" TEXT NOT NULL,
 "productoptionchoices3" TEXT NOT NULL,
 "productoptionname4" TEXT NOT NULL,
 "productoptiontype4" TEXT NOT NULL,
 "productoptionchoices4" TEXT NOT NULL,
 "productoptionname5" TEXT NOT NULL,
 "productoptiontype5" TEXT NOT NULL,
 "productoptionchoices5" TEXT NOT NULL,
 "productoptionname6" TEXT NOT NULL,
 "productoptiontype6" TEXT NOT NULL,
 "productoptionchoices6" TEXT NOT NULL,
 "modifiername1" TEXT NOT NULL,
 "modifiertype1" TEXT NOT NULL,
 "modifiercharlimit1" TEXT NOT NULL,
 "modifiermandatory1" TEXT NOT NULL,
 "modifierdescription1" TEXT NOT NULL,
 "modifiername2" TEXT NOT NULL,
 "modifiertype2" TEXT NOT NULL,
 "modifiercharlimit2" TEXT NOT NULL,
 "modifiermandatory2" TEXT NOT NULL,
 "modifierdescription2" TEXT NOT NULL,
 "modifiername3" TEXT NOT NULL,
 "modifiertype3" TEXT NOT NULL,
 "modifiercharlimit3" TEXT NOT NULL,
 "modifiermandatory3" TEXT NOT NULL,
 "modifierdescription3" TEXT NOT NULL,
 "modifiername4" TEXT NOT NULL,
 "modifiertype4" TEXT NOT NULL,
 "modifiercharlimit4" TEXT NOT NULL,
 "modifiermandatory4" TEXT NOT NULL,
 "modifierdescription4" TEXT NOT NULL,
 "modifiername5" TEXT NOT NULL,
 "modifiertype5" TEXT NOT NULL,
 "modifiercharlimit5" TEXT NOT NULL,
 "modifiermandatory5" TEXT NOT NULL,
 "modifierdescription5" TEXT NOT NULL,
 "modifiername6" TEXT NOT NULL,
 "modifiertype6" TEXT NOT NULL,
 "modifiercharlimit6" TEXT NOT NULL,
 "modifiermandatory6" TEXT NOT NULL,
 "modifierdescription6" TEXT NOT NULL,
 "modifiername7" TEXT NOT NULL,
 "modifiertype7" TEXT NOT NULL,
 "modifiercharlimit7" TEXT NOT NULL,
 "modifiermandatory7" TEXT NOT NULL,
 "modifierdescription7" TEXT NOT NULL,
 "modifiername8" TEXT NOT NULL,
 "modifiertype8" TEXT NOT NULL,
 "modifiercharlimit8" TEXT NOT NULL,
 "modifiermandatory8" TEXT NOT NULL,
 "modifierdescription8" TEXT NOT NULL,
 "modifiername9" TEXT NOT NULL,
 "modifiertype9" TEXT NOT NULL,
 "modifiercharlimit9" TEXT NOT NULL,
 "modifiermandatory9" TEXT NOT NULL,
 "modifierdescription9" TEXT NOT NULL,
 "modifiername10" TEXT NOT NULL,
 "modifiertype10" TEXT NOT NULL,
 "modifiercharlimit10" TEXT NOT NULL,
 "modifiermandatory10" TEXT NOT NULL,
 "modifierdescription10" TEXT NOT NULL,
 PRIMARY KEY(batch_id,source_row)
);
CREATE TABLE IF NOT EXISTS wix_orders (
 batch_id TEXT NOT NULL REFERENCES wix_import_batches(id), source_row INTEGER NOT NULL,
 "order_number" TEXT NOT NULL,
 "date_created" TEXT NOT NULL,
 "time" TEXT NOT NULL,
 "fulfill_by" TEXT NOT NULL,
 "total_order_quantity" TEXT NOT NULL,
 "contact_email" TEXT NOT NULL,
 "note_from_customer" TEXT NOT NULL,
 "additional_checkout_info" TEXT NOT NULL,
 "business_location" TEXT NOT NULL,
 "tags" TEXT NOT NULL,
 "order_id" TEXT NOT NULL,
 "delivery_method" TEXT NOT NULL,
 "delivery_time" TEXT NOT NULL,
 "recipient_name" TEXT NOT NULL,
 "recipient_phone" TEXT NOT NULL,
 "recipient_company_name" TEXT NOT NULL,
 "delivery_country" TEXT NOT NULL,
 "delivery_state" TEXT NOT NULL,
 "delivery_state_name" TEXT NOT NULL,
 "delivery_city" TEXT NOT NULL,
 "delivery_address" TEXT NOT NULL,
 "delivery_zip_postal_code" TEXT NOT NULL,
 "billing_name" TEXT NOT NULL,
 "billing_phone" TEXT NOT NULL,
 "billing_company_name" TEXT NOT NULL,
 "billing_country" TEXT NOT NULL,
 "billing_state" TEXT NOT NULL,
 "billing_state_name" TEXT NOT NULL,
 "billing_city" TEXT NOT NULL,
 "billing_address" TEXT NOT NULL,
 "billing_zip_postal_code" TEXT NOT NULL,
 "payment_status" TEXT NOT NULL,
 "payment_method" TEXT NOT NULL,
 "global_coupon_code" TEXT NOT NULL,
 "global_discount_amount" TEXT NOT NULL,
 "gift_card_amount" TEXT NOT NULL,
 "shipping_rate" TEXT NOT NULL,
 "total_tax" TEXT NOT NULL,
 "total" TEXT NOT NULL,
 "currency" TEXT NOT NULL,
 "refunded_amount" TEXT NOT NULL,
 "net_amount" TEXT NOT NULL,
 "additional_fees" TEXT NOT NULL,
 "amount_paid" TEXT NOT NULL,
 "fulfillment_status" TEXT NOT NULL,
 "item_fulfillment_locations" TEXT NOT NULL,
 "tracking_number" TEXT NOT NULL,
 "fulfillment_service" TEXT NOT NULL,
 "shipping_label" TEXT NOT NULL,
 PRIMARY KEY(batch_id,source_row)
);
CREATE TABLE IF NOT EXISTS wix_items (
 batch_id TEXT NOT NULL REFERENCES wix_import_batches(id), source_row INTEGER NOT NULL,
 "order_number" TEXT NOT NULL,
 "date_created" TEXT NOT NULL,
 "time" TEXT NOT NULL,
 "fulfill_by" TEXT NOT NULL,
 "total_order_quantity" TEXT NOT NULL,
 "contact_email" TEXT NOT NULL,
 "note_from_customer" TEXT NOT NULL,
 "additional_checkout_info" TEXT NOT NULL,
 "business_location" TEXT NOT NULL,
 "tags" TEXT NOT NULL,
 "order_id" TEXT NOT NULL,
 "item" TEXT NOT NULL,
 "fulfillment_location" TEXT NOT NULL,
 "variant" TEXT NOT NULL,
 "modifiers_add_ons" TEXT NOT NULL,
 "sku" TEXT NOT NULL,
 "qty" TEXT NOT NULL,
 "quantity_refunded" TEXT NOT NULL,
 "price" TEXT NOT NULL,
 "item_coupon_code" TEXT NOT NULL,
 "item_discount_amount" TEXT NOT NULL,
 "weight" TEXT NOT NULL,
 "custom_text" TEXT NOT NULL,
 "deposit_amount" TEXT NOT NULL,
 "delivery_method" TEXT NOT NULL,
 "delivery_time" TEXT NOT NULL,
 "recipient_name" TEXT NOT NULL,
 "recipient_phone" TEXT NOT NULL,
 "recipient_company_name" TEXT NOT NULL,
 "delivery_country" TEXT NOT NULL,
 "delivery_state" TEXT NOT NULL,
 "delivery_state_name" TEXT NOT NULL,
 "delivery_city" TEXT NOT NULL,
 "delivery_address" TEXT NOT NULL,
 "delivery_zip_postal_code" TEXT NOT NULL,
 "billing_name" TEXT NOT NULL,
 "billing_phone" TEXT NOT NULL,
 "billing_company_name" TEXT NOT NULL,
 "billing_country" TEXT NOT NULL,
 "billing_state" TEXT NOT NULL,
 "billing_state_name" TEXT NOT NULL,
 "billing_city" TEXT NOT NULL,
 "billing_address" TEXT NOT NULL,
 "billing_zip_postal_code" TEXT NOT NULL,
 "payment_status" TEXT NOT NULL,
 "payment_method" TEXT NOT NULL,
 "global_coupon_code" TEXT NOT NULL,
 "global_discount_amount" TEXT NOT NULL,
 "gift_card_amount" TEXT NOT NULL,
 "shipping_rate" TEXT NOT NULL,
 "total_tax" TEXT NOT NULL,
 "total" TEXT NOT NULL,
 "currency" TEXT NOT NULL,
 "refunded_amount" TEXT NOT NULL,
 "net_amount" TEXT NOT NULL,
 "additional_fees" TEXT NOT NULL,
 "amount_paid" TEXT NOT NULL,
 "fulfillment_status" TEXT NOT NULL,
 "item_fulfillment_locations" TEXT NOT NULL,
 "tracking_number" TEXT NOT NULL,
 "fulfillment_service" TEXT NOT NULL,
 "shipping_label" TEXT NOT NULL,
 PRIMARY KEY(batch_id,source_row)
);
CREATE TABLE IF NOT EXISTS wix_contacts (
 batch_id TEXT NOT NULL REFERENCES wix_import_batches(id), source_row INTEGER NOT NULL,
 "first_name" TEXT NOT NULL,
 "last_name" TEXT NOT NULL,
 "email_1" TEXT NOT NULL,
 "phone_1" TEXT NOT NULL,
 "phone_2" TEXT NOT NULL,
 "phone_3" TEXT NOT NULL,
 "address_1_type" TEXT NOT NULL,
 "address_1_street" TEXT NOT NULL,
 "address_1_street_line_2" TEXT NOT NULL,
 "address_1_city" TEXT NOT NULL,
 "address_1_state_region" TEXT NOT NULL,
 "address_1_zip" TEXT NOT NULL,
 "address_1_country" TEXT NOT NULL,
 "address_2_type" TEXT NOT NULL,
 "address_2_street" TEXT NOT NULL,
 "address_2_street_line_2" TEXT NOT NULL,
 "address_2_city" TEXT NOT NULL,
 "address_2_state_region" TEXT NOT NULL,
 "address_2_zip" TEXT NOT NULL,
 "address_2_country" TEXT NOT NULL,
 "address_3_type" TEXT NOT NULL,
 "address_3_street" TEXT NOT NULL,
 "address_3_street_line_2" TEXT NOT NULL,
 "address_3_city" TEXT NOT NULL,
 "address_3_state_region" TEXT NOT NULL,
 "address_3_zip" TEXT NOT NULL,
 "address_3_country" TEXT NOT NULL,
 "address_4_type" TEXT NOT NULL,
 "address_4_street" TEXT NOT NULL,
 "address_4_street_line_2" TEXT NOT NULL,
 "address_4_city" TEXT NOT NULL,
 "address_4_state_region" TEXT NOT NULL,
 "address_4_zip" TEXT NOT NULL,
 "address_4_country" TEXT NOT NULL,
 "address_5_type" TEXT NOT NULL,
 "address_5_street" TEXT NOT NULL,
 "address_5_street_line_2" TEXT NOT NULL,
 "address_5_city" TEXT NOT NULL,
 "address_5_state_region" TEXT NOT NULL,
 "address_5_zip" TEXT NOT NULL,
 "address_5_country" TEXT NOT NULL,
 "address_6_type" TEXT NOT NULL,
 "address_6_street" TEXT NOT NULL,
 "address_6_street_line_2" TEXT NOT NULL,
 "address_6_city" TEXT NOT NULL,
 "address_6_state_region" TEXT NOT NULL,
 "address_6_zip" TEXT NOT NULL,
 "address_6_country" TEXT NOT NULL,
 "address_7_type" TEXT NOT NULL,
 "address_7_street" TEXT NOT NULL,
 "address_7_street_line_2" TEXT NOT NULL,
 "address_7_city" TEXT NOT NULL,
 "address_7_state_region" TEXT NOT NULL,
 "address_7_zip" TEXT NOT NULL,
 "address_7_country" TEXT NOT NULL,
 "address_8_type" TEXT NOT NULL,
 "address_8_street" TEXT NOT NULL,
 "address_8_street_line_2" TEXT NOT NULL,
 "address_8_city" TEXT NOT NULL,
 "address_8_state_region" TEXT NOT NULL,
 "address_8_zip" TEXT NOT NULL,
 "address_8_country" TEXT NOT NULL,
 "address_9_type" TEXT NOT NULL,
 "address_9_street" TEXT NOT NULL,
 "address_9_street_line_2" TEXT NOT NULL,
 "address_9_city" TEXT NOT NULL,
 "address_9_state_region" TEXT NOT NULL,
 "address_9_zip" TEXT NOT NULL,
 "address_9_country" TEXT NOT NULL,
 "address_10_type" TEXT NOT NULL,
 "address_10_street" TEXT NOT NULL,
 "address_10_city" TEXT NOT NULL,
 "address_10_state_region" TEXT NOT NULL,
 "address_10_zip" TEXT NOT NULL,
 "address_10_country" TEXT NOT NULL,
 "company" TEXT NOT NULL,
 "labels" TEXT NOT NULL,
 "created_at_utc_0" TEXT NOT NULL,
 "email_subscriber_status" TEXT NOT NULL,
 "sms_subscriber_status" TEXT NOT NULL,
 "last_activity" TEXT NOT NULL,
 "last_activity_date_utc_0" TEXT NOT NULL,
 "source" TEXT NOT NULL,
 "language" TEXT NOT NULL,
 "message" TEXT NOT NULL,
 "subject" TEXT NOT NULL,
 PRIMARY KEY(batch_id,source_row)
);
CREATE INDEX IF NOT EXISTS idx_wix_orders_identity ON wix_orders(batch_id,"order_id");
CREATE INDEX IF NOT EXISTS idx_wix_items_identity ON wix_items(batch_id,"order_id");
CREATE INDEX IF NOT EXISTS idx_wix_contacts_identity ON wix_contacts(batch_id,"email_1");
CREATE INDEX IF NOT EXISTS idx_wix_products_identity ON wix_products(batch_id,"handle");
CREATE TABLE IF NOT EXISTS wix_record_work (
 batch_id TEXT NOT NULL REFERENCES wix_import_batches(id), dataset TEXT NOT NULL CHECK(dataset IN ('orders','items','contacts','products')),
 source_row INTEGER NOT NULL, review_state TEXT NOT NULL DEFAULT 'needs_review' CHECK(review_state IN ('needs_review','reviewed','follow_up')),
 notes TEXT NOT NULL DEFAULT '', updated_by TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT (datetime('now')),
 PRIMARY KEY(batch_id,dataset,source_row)
);
CREATE TABLE IF NOT EXISTS wix_review_audit (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 actor_email TEXT NOT NULL,
 batch_id TEXT NOT NULL,
 dataset TEXT NOT NULL CHECK(dataset IN ('orders','items','contacts','products')),
 source_row INTEGER NOT NULL,
 review_state TEXT NOT NULL CHECK(review_state IN ('needs_review','reviewed','follow_up')),
 created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
