// Reads a Wix "Export Products to CSV" file and generates d1/seed.sql for the
// products/skus tables — including real content (slug, description, image,
// categories) migrated from Wix, with images downloaded and rehosted under
// public/media/live-site-products/ so the site has no runtime dependency on
// Wix's CDN. Re-run whenever the Wix catalog is re-exported.
//
// Usage: node scripts/generate-d1-seed.mjs <path-to-catalog_products.csv>

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, extname } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const srcPath = process.argv[2]
if (!srcPath) {
  console.error('Usage: node scripts/generate-d1-seed.mjs <path-to-catalog_products.csv>')
  process.exit(1)
}

// Wix "collection" text -> this site's real category taxonomy (src/App.jsx `categories` const).
// A product can map to more than one slug (e.g. "Special Deal;Salt Lamps").
const CATEGORY_MAP = {
  'salt lamps': 'salt-lamps',
  'candle holders': 'candle-holders',
  'rock salt pantry items': 'rock-salt-pantry-items',
  'rock salt bricks': 'rock-salt-bricks',
  'equestrian / salt licks': 'equestrian-salt-licks',
  'himalyan salt massage & relaxation products': 'himalayan-salt-massage-relaxation-products',
  'accessories': 'accessories',
  'special deal': 'special-deal',
}

function mapCategories(rawCollection) {
  const parts = rawCollection.split(';').map(s => s.trim().toLowerCase()).filter(Boolean)
  const slugs = new Set(['all-products'])
  for (const part of parts) {
    const slug = CATEGORY_MAP[part]
    if (slug) slugs.add(slug)
  }
  return [...slugs]
}

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function stripHtmlAndTruncate(html, maxLen = 200) {
  const text = html
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')
    .trim()
  if (text.length <= maxLen) return text
  const cut = text.slice(0, maxLen)
  const lastSpace = cut.lastIndexOf(' ')
  return `${cut.slice(0, lastSpace > 0 ? lastSpace : maxLen)}…`
}

function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++ } else { inQuotes = false }
      } else {
        field += c
      }
    } else if (c === '"') {
      inQuotes = true
    } else if (c === ',') {
      row.push(field); field = ''
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++
      row.push(field); field = ''
      if (row.length > 1 || row[0] !== '') rows.push(row)
      row = []
    } else {
      field += c
    }
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row) }
  return rows
}

const raw = readFileSync(resolve(srcPath), 'utf-8').replace(/^﻿/, '')
const [header, ...rows] = parseCsv(raw)
const idx = Object.fromEntries(header.map((h, i) => [h, i]))
const get = (row, field) => (row[idx[field]] ?? '').trim()

const groups = new Map()
const order = []
for (const row of rows) {
  const hid = get(row, 'handleId')
  if (!hid) continue
  if (!groups.has(hid)) { groups.set(hid, []); order.push(hid) }
  groups.get(hid).push(row)
}

const escSql = s => `'${String(s).replace(/'/g, "''")}'`
const toPence = priceStr => {
  const n = parseFloat(priceStr)
  return Number.isFinite(n) ? Math.round(n * 100) : 0
}

const mediaDir = resolve(__dirname, '../public/media/live-site-products')
if (!existsSync(mediaDir)) mkdirSync(mediaDir, { recursive: true })

async function downloadHeroImage(handleId, imageUrlField) {
  const firstFile = imageUrlField.split(';')[0]?.trim()
  if (!firstFile) return ''
  const ext = extname(firstFile) || '.jpg'
  const localName = `wix-${handleId.replace(/^product_/, '').slice(0, 12)}${ext}`
  const localPath = resolve(mediaDir, localName)
  const publicPath = `/media/live-site-products/${localName}`
  if (existsSync(localPath)) return publicPath // idempotent — skip re-download

  const url = `https://static.wixstatic.com/media/${firstFile}`
  const res = await fetch(url)
  if (!res.ok) {
    console.warn(`  ! image download failed (${res.status}): ${url}`)
    return ''
  }
  const buf = Buffer.from(await res.arrayBuffer())
  writeFileSync(localPath, buf)
  return publicPath
}

const lines = [
  '-- Generated by scripts/generate-d1-seed.mjs — do not hand-edit, re-run the script instead.',
  '-- Apply with: wrangler d1 execute salty-lamps-db --file=d1/seed.sql',
  '--',
  '-- Deliberately never touches orders/order_items — a catalog re-sync must not be able to',
  '-- wipe order history. KNOWN LIMITATION: this still deletes+reinserts skus, so once real',
  '-- orders exist, re-running this will orphan order_items.sku_id (skus.id is autoincrement).',
  '-- Fix before go-live: switch to an UPSERT keyed on (product_id, sku) instead of delete+insert.',
  '',
  'DELETE FROM skus;',
  'DELETE FROM products;',
  '',
]

console.log(`Migrating ${order.length} products (downloading hero images where missing)...`)

for (const hid of order) {
  const grp = groups.get(hid)
  const productRow = grp.find(r => get(r, 'fieldType') === 'Product')
  const variantRows = grp.filter(r => get(r, 'fieldType') === 'Variant')
  if (!productRow) continue

  const name = get(productRow, 'name')
  const rawCollection = get(productRow, 'collection')
  const categories = mapCategories(rawCollection)
  const visible = get(productRow, 'visible') === 'true' ? 1 : 0
  const slug = slugify(name)
  const description = stripHtmlAndTruncate(get(productRow, 'description'))
  const image = await downloadHeroImage(hid, get(productRow, 'productImageUrl'))

  lines.push(
    `INSERT INTO products (id, name, slug, description, image, categories, tags, visible) VALUES (${escSql(hid)}, ${escSql(name)}, ${escSql(slug)}, ${escSql(description)}, ${escSql(image)}, ${escSql(categories.join(','))}, ${escSql('')}, ${visible});`
  )

  const skuRows = variantRows.length ? variantRows : [productRow]
  for (const r of skuRows) {
    const sku = get(r, 'sku') || `${hid}-default`
    const opt1 = get(r, 'productOptionDescription1')
    const opt2 = get(r, 'productOptionDescription2')
    const variantLabel = [opt1, opt2].filter(Boolean).join(' / ')
    const priceStr = get(r, 'price') || get(productRow, 'price')
    const invRaw = get(r, 'inventory')
    const trackMode = (invRaw === 'InStock' || invRaw === 'OutOfStock') ? 'binary' : 'quantity'
    const quantity = trackMode === 'quantity' ? (parseInt(invRaw, 10) || 0) : 'NULL'
    const inStock = trackMode === 'binary' ? (invRaw === 'InStock' ? 1 : 0) : (parseInt(invRaw, 10) > 0 ? 1 : 0)

    lines.push(
      `INSERT INTO skus (sku, product_id, variant_label, price_pence, track_mode, quantity, in_stock) VALUES (${escSql(sku)}, ${escSql(hid)}, ${escSql(variantLabel)}, ${toPence(priceStr)}, ${escSql(trackMode)}, ${quantity}, ${inStock}); -- sku not unique in source data`
    )
  }
}

const outPath = resolve(__dirname, '../d1/seed.sql')
writeFileSync(outPath, lines.join('\n') + '\n', 'utf-8')
console.log(`Wrote ${lines.length} SQL statements to ${outPath}`)
