-- Removes demo data generated by scripts/generate-demo-orders-seed.mjs.
--
-- Scoped delete — only removes rows whose id starts with 'demo_order_', never a blanket wipe.
-- Safe to run even after real orders exist: real Stripe checkout session ids never start with
-- this prefix, so real order history is untouched. Run this before going live.
--
-- LOCAL/TESTING USE ONLY.
-- Apply: wrangler d1 execute salty-lamps-db --local --file=d1/reset-demo-orders.sql

DELETE FROM order_items WHERE order_id LIKE 'demo_order_%';
DELETE FROM orders WHERE id LIKE 'demo_order_%';
