import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

async function setup(page,request,items=[{skuId:129,qty:2}],deliveryRoute=null) {
 const data=await (await request.get('/api/products')).json()
 const base=data.products[0]
 data.products=data.products.filter(p=>![129,131,133].includes(p.skuId))
 for(const [skuId,weight,price,stockQty] of [[129,1000,3.99,20],[131,5000,11.99,4],[133,10000,16.99,0]]) {
  data.products.push({...base,id:`sku-${skuId}`,skuId,productId:'fixture-salt',productName:'Culinary salt',name:`Culinary salt — ${weight/1000}Kg / Fine`,variantLabel:`${weight/1000}Kg / Fine`,slug:`fixture-salt-${skuId}`,price,stock:stockQty>0,stockQty,productWeightMinG:weight,productWeightMaxG:weight,deliveryNeedsConfirmation:false})
 }
 await page.route('**/api/products',r=>r.fulfill({json:data}))
 await page.addInitScript(items=>{if(!sessionStorage.getItem('salty-lamps-cart'))sessionStorage.setItem('salty-lamps-cart',JSON.stringify(items))},items)
 await page.route('**/api/checkout/delivery',deliveryRoute || (r=>{
  const items=r.request().postDataJSON().items
  const weight=items.reduce((s,i)=>s+(i.skuId===129?1000:5000)*i.quantity,0)
  return r.fulfill({json:{status:'ready',totalWeightG:weight,options:[{service:'Fixture delivery',pricePence:weight>3000?799:399}]}})
 }))
 await page.goto('/shop')
 await page.locator('.cart-button').click()
 return page.getByRole('dialog',{name:'Shopping cart'})
}

async function enterAddress(page) {
 await page.getByRole('button',{name:'Continue to address',exact:true}).click()
 await expect(page).toHaveURL(/\/checkout\/address$/)
 if(process.env.REVIEW_SCREENSHOTS) await page.screenshot({path:'/tmp/salty-lamps-address-empty.png',fullPage:true})
 await fillAddress(page)
}

async function fillAddress(page) {
 await page.getByLabel('Email address').fill('buyer@example.com')
 await page.getByLabel('Full name').fill('Example Buyer')
 await page.getByLabel('Address line 1').fill('10 High Street')
 await page.getByLabel('Town or city').fill('Stoke-on-Trent')
}

test('weight changes update price, total product weight, shipping and saved option',async({page,request})=>{
 const cart=await setup(page,request)
 await expect(cart.locator('.cart-option')).toContainText('1 kg')
 await cart.getByRole('combobox').selectOption('131')
 await expect(cart.getByRole('spinbutton')).toHaveValue('2')
 await expect(cart.locator('.cart-line-total strong')).toHaveText('£23.98')
 await expect(cart.locator('.cart-option')).toContainText('10 kg for 2')
 await expect(cart.locator('.cart-total strong')).toHaveText('£31.97')
 await expect(cart.getByRole('combobox')).toBeFocused()
 await cart.getByRole('button',{name:'Checkout',exact:true}).click()
 await expect(page).toHaveURL(/\/checkout$/)
 await expect(page.getByRole('heading',{name:'Review your order'})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Review your order'})).toBeFocused()
 await expect(page.getByRole('main').getByRole('combobox',{name:/Weight, size or pack/})).toHaveValue('131')
 const saved=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('salty-lamps-cart')))
 expect(saved).toEqual([{skuId:131,qty:2}])
 await page.reload()
 await expect(page.getByRole('main').getByRole('combobox',{name:/Weight, size or pack/})).toHaveValue('131')
 await expect(page.getByRole('main').getByRole('spinbutton')).toHaveValue('2')
 const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(results.violations.map(v=>v.id)).toEqual([])
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
 if(process.env.REVIEW_SCREENSHOTS) await page.screenshot({path:`../outputs/asim-test-suite/order-review-${test.info().project.name}.png`,fullPage:true})
})

test('changing to an existing option merges quantities and respects stock limits',async({page,request})=>{
 const cart=await setup(page,request,[{skuId:129,qty:2},{skuId:131,qty:3}])
 await cart.getByRole('combobox').first().selectOption('131')
 await expect(cart.getByRole('status').filter({hasText:'Only 4'})).toBeVisible()
 await expect(cart.locator('.cart-line')).toHaveCount(2)
 await cart.getByRole('spinbutton').first().fill('1')
 await cart.getByRole('combobox').first().selectOption('131')
 await expect(cart.locator('.cart-line')).toHaveCount(1)
 await expect(cart.getByRole('spinbutton')).toHaveValue('4')
 await expect(cart.getByRole('combobox')).toHaveValue('131')
 await expect(cart.locator('.cart-line-total strong')).toHaveText('£47.96')
 await expect(cart.locator('option[value="133"]')).toHaveAttribute('disabled','')
})

test('order review passes the changed option and quantity into secure checkout',async({page,request})=>{
 const cart=await setup(page,request)
 await cart.getByRole('button',{name:'Checkout',exact:true}).click()
 const main=page.getByRole('main')
 await main.getByRole('combobox',{name:/Weight, size or pack/}).selectOption('131')
 await expect(main.locator('.cart-total strong')).toHaveText('£31.97')
 let payload
 await page.route('**/api/checkout',r=>{payload=r.request().postDataJSON();return r.fulfill({json:{clientSecret:'cs_test_secret_fixture',publishableKey:'pk_test_fixture',sessionId:'cs_test_review'}})})
 await main.getByLabel('Delivery postcode').fill('ST4 3NP')
 await enterAddress(page)
 await main.getByRole('button',{name:'Continue to payment',exact:true}).click()
 await expect(page).toHaveURL(/\/checkout\/payment$/)
 await expect(page.locator('.site-header')).toBeVisible()
 await expect(main.getByRole('heading',{name:'Payment method'})).toBeVisible()
 expect(payload.items).toEqual([{skuId:131,quantity:2}])
 expect(payload.address).toMatchObject({email:'buyer@example.com',line1:'10 High Street',postcode:'ST4 3NP'})
})

test('reviewed postcode stays fixed on the UK address and payment payload',async({page,request})=>{
 const cart=await setup(page,request,[{skuId:129,qty:2}],r=>{
  const body=r.request().postDataJSON()
  const pricePence=body.postcode==='ST4 3NP'?450:799
  return r.fulfill({json:{status:'ready',totalWeightG:2000,options:[{service:'Fixture delivery',pricePence,parcelCount:1}]}})
 })
 await cart.getByRole('button',{name:'Checkout',exact:true}).click()
 const main=page.getByRole('main')
 await main.getByLabel('Delivery postcode').fill('ST4 3NP')
 await expect(main.locator('.cart-total strong')).toHaveText('£12.48')
 let payload
 await page.route('**/api/checkout',r=>{payload=r.request().postDataJSON();return r.fulfill({json:{clientSecret:'cs_test_secret_fixture',publishableKey:'pk_test_fixture',sessionId:'cs_test_postcode'}})})
 await enterAddress(page)
 await expect(main.getByLabel('Delivery postcode')).toHaveValue('ST4 3NP')
 await expect(main.getByLabel('Country')).toHaveValue('United Kingdom')
 await expect(main.getByLabel('Delivery postcode')).toHaveAttribute('readonly','')
 await expect(main.getByLabel('Address line 1')).toHaveAttribute('autocomplete','off')
 await expect(main.getByRole('heading',{name:'Email',exact:true})).toHaveCSS('font-size',await main.getByRole('heading',{name:'Shipping address'}).evaluate(element=>getComputedStyle(element).fontSize))
 const accessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(accessibility.violations.map(v=>v.id)).toEqual([])
 if(process.env.REVIEW_SCREENSHOTS) await page.screenshot({path:'/tmp/salty-lamps-address-review.png',fullPage:true})
 await main.getByRole('button',{name:'Continue to payment',exact:true}).click()
 await expect(page).toHaveURL(/\/checkout\/payment$/)
 await expect(page.locator('.site-header')).toBeVisible()
 expect(payload.postcode).toBe('ST4 3NP')
 expect(payload.address.city).toBe('Stoke-on-Trent')
})

test('special instructions are optional, counted, kept through a postcode change and sent with the address',async({page,request})=>{
 const cart=await setup(page,request)
 await cart.getByRole('button',{name:'Checkout',exact:true}).click()
 const main=page.getByRole('main')
 let payload
 await page.route('**/api/checkout',r=>{payload=r.request().postDataJSON();return r.fulfill({json:{clientSecret:'cs_test_secret_fixture',publishableKey:'pk_test_fixture',sessionId:'cs_test_instructions'}})})
 await main.getByLabel('Delivery postcode').fill('ST4 3NP')
 await enterAddress(page)
 const box=main.getByRole('textbox',{name:/Instructions for this order/})
 const count=main.locator('#checkout-instructions-count')
 await expect(main.getByRole('heading',{name:'Special instructions'})).toBeVisible()
 await expect(box).toBeVisible()
 await expect(box).toHaveAccessibleName('Instructions for this order (optional)')
 await expect(box).toHaveJSProperty('required',false)
 await expect(box).toHaveAttribute('maxlength','500')
 await expect(box).toHaveAttribute('aria-describedby','checkout-instructions-help checkout-instructions-count')
 await expect(count).toHaveText('0 / 500')
 const text='Leave with the neighbour at no. 12'
 await box.fill(text)
 await expect(count).toHaveText(`${text.length} / 500`)
 await expect(count).toHaveText('34 / 500')
 await expect(count).not.toHaveClass(/is-near-limit/)
 await box.fill('x'.repeat(460))
 await expect(count).toHaveText('460 / 500')
 await expect(count).toHaveClass(/is-near-limit/)
 const accessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
 expect(accessibility.violations.map(v=>v.id)).toEqual([])
 await box.fill(text)
 await main.getByRole('button',{name:'Change postcode'}).click()
 await main.getByLabel('Delivery postcode').fill('ST4 4AA')
 await main.getByRole('button',{name:'Continue to address',exact:true}).click()
 await expect(page).toHaveURL(/\/checkout\/address$/)
 await expect(main.getByLabel('Delivery postcode')).toHaveValue('ST4 4AA')
 await expect(main.getByLabel('Address line 1')).toHaveValue('')
 await expect(box).toHaveValue(text)
 await fillAddress(page)
 await box.fill(`${text}  `)
 await main.getByRole('button',{name:'Continue to payment',exact:true}).click()
 await expect(page).toHaveURL(/\/checkout\/payment$/)
 expect(payload.address.instructions).toBe(text)
})

test('an empty instructions box never blocks payment and is not sent',async({page,request})=>{
 const cart=await setup(page,request)
 await cart.getByRole('button',{name:'Checkout',exact:true}).click()
 const main=page.getByRole('main')
 let payload
 await page.route('**/api/checkout',r=>{payload=r.request().postDataJSON();return r.fulfill({json:{clientSecret:'cs_test_secret_fixture',publishableKey:'pk_test_fixture',sessionId:'cs_test_no_instructions'}})})
 await main.getByLabel('Delivery postcode').fill('ST4 3NP')
 await enterAddress(page)
 await expect(main.getByRole('textbox',{name:/Instructions for this order/})).toHaveValue('')
 await main.getByRole('button',{name:'Continue to payment',exact:true}).click()
 await expect(page).toHaveURL(/\/checkout\/payment$/)
 expect(Object.keys(payload.address)).toEqual(['email','name','line1','line2','city','postcode'])
})

test('postcode suggestions on order review stay fixed through address entry',async({page,request})=>{
 const cart=await setup(page,request)
 if(!process.env.LIVE_POSTCODE) await page.route('**/api/postcode-suggestions?*',route=>{
  const query=new URL(route.request().url()).searchParams.get('query').replace(/\s/g,'').toUpperCase()
  const suggestions=['SW1A 2AA','SW1A 1AA'].filter(value=>value.replace(/\s/g,'').startsWith(query))
  return route.fulfill({json:{suggestions}})
 })
 await cart.getByRole('button',{name:'Checkout',exact:true}).click()
 const main=page.getByRole('main')
 const reviewPostcode=main.getByRole('combobox',{name:'Delivery postcode'})
 await reviewPostcode.fill('SW1A 2A')
 await main.getByRole('option',{name:'SW1A 2AA'}).click()
 await expect(reviewPostcode).toHaveValue('SW1A 2AA')
 await expect(reviewPostcode).toHaveAttribute('autocomplete','off')
 await main.getByRole('button',{name:'Continue to address',exact:true}).click()
 await expect(page).toHaveURL(/\/checkout\/address$/)
 const addressPostcode=main.getByLabel('Delivery postcode')
 await expect(addressPostcode).toHaveValue('SW1A 2AA')
 await expect(addressPostcode).toHaveAttribute('readonly','')
 await expect(main.getByLabel('Address line 1')).toHaveAttribute('autocomplete','off')
 await main.getByRole('button',{name:'Change postcode'}).click()
 await reviewPostcode.fill('SW1A 1')
 await main.getByRole('option',{name:'SW1A 1AA'}).click()
 await expect(reviewPostcode).toHaveValue('SW1A 1AA')
 await main.getByRole('button',{name:'Continue to address',exact:true}).click()
 await expect(addressPostcode).toHaveValue('SW1A 1AA')
})

test('internal delivery gaps stay private and the payment action remains available',async({page,request})=>{
 const cart=await setup(page,request)
 await page.route('**/api/checkout/delivery',r=>r.fulfill({json:{status:'needs_review',message:'Delivery needs confirmation.',itemsNeedingDelivery:[{skuId:129,name:'Test salt'}],options:[]}}))
 await cart.getByRole('button',{name:'Checkout',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Review your order'})).toBeVisible()
 const main=page.getByRole('main')
 await expect(main).not.toContainText(/Delivery needs confirmation|Test salt|packed weight/i)
 await expect(main.getByRole('button',{name:'Get help with delivery',exact:true})).toHaveCount(0)
 await expect(main.getByRole('button',{name:'Continue to address',exact:true})).toBeEnabled()
})

test('an empty review has a route back to shopping',async({page})=>{
 await page.goto('/checkout')
 await expect(page.getByRole('heading',{name:'Your cart is empty',exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'Browse the shop',exact:true})).toHaveAttribute('href','/shop')
})
